import PDFDocument from 'pdfkit';
import * as qr from 'qr-image';
import { PassThrough } from 'stream';

interface ProofData {
  id: string;
  circuit_type: string;
  claim_type: string;
  status: string;
  created_at: string;
  public_token: string;
  proof_time_ms?: number;
}

export function generateProofPDF(proof: ProofData, baseUrl: string): PassThrough {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    info: {
      Title: 'StellarID Verification Certificate',
      Author: 'StellarID',
    },
  });

  const stream = new PassThrough();
  doc.pipe(stream);

  const isVerified = proof.status === 'verified';
  const primaryColor = isVerified ? '#00c853' : '#ef4444';
  const verifyUrl = `${baseUrl}/verify/${proof.public_token}`;

  // Header bar
  doc.rect(0, 0, 595, 100).fill('#0a0020');
  doc.fontSize(28).fillColor('#ffffff').text('StellarID', 50, 30, { continued: true });
  doc.fontSize(12).fillColor('#00e676').text('  VERIFICATION CERTIFICATE', { baseline: 'alphabetic' });
  doc.fontSize(9).fillColor('rgba(255,255,255,0.5)').text('Decentralized Identity Verification Protocol', 50, 65);

  // Status badge
  const badgeY = 130;
  const badgeWidth = 200;
  doc.roundedRect(50, badgeY, badgeWidth, 45, 8).fill(isVerified ? '#00c85315' : '#ef444415');
  doc.roundedRect(50, badgeY, badgeWidth, 45, 8).lineWidth(1.5).stroke(primaryColor);
  doc.fontSize(18).fillColor(primaryColor).text(
    isVerified ? 'VERIFIED' : 'REVOKED',
    50, badgeY + 12,
    { width: badgeWidth, align: 'center' }
  );

  // Details section
  const detailsY = 210;
  const lineHeight = 35;

  const drawField = (label: string, value: string, y: number) => {
    doc.fontSize(9).fillColor('#666666').text(label.toUpperCase(), 50, y);
    doc.fontSize(13).fillColor('#1a1a2e').text(value, 50, y + 14);
    doc.moveTo(50, y + 32).lineTo(400, y + 32).lineWidth(0.5).stroke('#e0e0e0');
  };

  drawField('Claim Type', proof.claim_type || proof.circuit_type, detailsY);
  drawField('Circuit', proof.circuit_type, detailsY + lineHeight);
  drawField('Proof ID', proof.id.substring(0, 20) + '...', detailsY + lineHeight * 2);
  drawField('Verified At', new Date(proof.created_at).toLocaleString('en-US', {
    dateStyle: 'long', timeStyle: 'short'
  }), detailsY + lineHeight * 3);

  if (proof.proof_time_ms) {
    drawField('Proof Time', `${(proof.proof_time_ms / 1000).toFixed(2)} seconds`, detailsY + lineHeight * 4);
  }

  // QR Code
  const qrY = detailsY;
  try {
    const qrPng = qr.imageSync(verifyUrl, { type: 'png', size: 5, margin: 1 });
    doc.image(qrPng, 430, qrY, { width: 110, height: 110 });
    doc.fontSize(7).fillColor('#999999').text('Scan to verify', 430, qrY + 115, { width: 110, align: 'center' });
  } catch {
    doc.fontSize(8).fillColor('#999').text('QR unavailable', 430, qrY + 40);
  }

  // Verification link
  const linkY = 470;
  doc.roundedRect(50, linkY, 495, 50, 6).fill('#f5f5ff');
  doc.fontSize(8).fillColor('#666').text('VERIFICATION LINK', 65, linkY + 10);
  doc.fontSize(9).fillColor('#7c3aed').text(verifyUrl, 65, linkY + 25, { link: verifyUrl });

  // Footer
  const footerY = 750;
  doc.moveTo(50, footerY).lineTo(545, footerY).lineWidth(0.5).stroke('#e0e0e0');
  doc.fontSize(7).fillColor('#999999')
    .text('This certificate was generated by StellarID — a decentralized identity verification platform.', 50, footerY + 10)
    .text('Zero personal data is stored or transmitted. Verification uses zero-knowledge proofs on Stellar blockchain.', 50, footerY + 22)
    .text(`Generated: ${new Date().toISOString()}`, 50, footerY + 38);

  doc.end();
  return stream;
}
